# Core.UDP CI Pipeline
name: 1.0.0.$(rev:r)
variables: 
- name: Project.Path
  value: $(Build.SourcesDirectory)/Models/PolyhydraSoftware.Core.UDP.csproj
- name: Test.Path
  value: $(Build.SourcesDirectory)/Tests/PolyhydraSoftware.Core.UDP.Test.csproj

trigger:
  branches:
    include:
    - refs/heads/main

jobs:
- job: Phase_1 
  cancelTimeoutInMinutes: 1
  pool:
    name: Default
  steps:
  - checkout: self
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      projects: '$(Project.Path)'
      arguments: --configuration Release
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      projects: '$(Test.Path)'
      arguments: --configuration Release --no-build
  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: pack
      packagesToPack: '$(Project.Path)' 
      versioningScheme: 'byBuildNumber'
      arguments: --configuration Release --no-build
  - task: NuGetCommand@2
    displayName: Poly NuGet push
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      feedPublish: 015fc12f-cd63-4ab4-8d6a-dc889e53bf70
      allowPackageConflicts: false
  - task: NuGetCommand@2
    inputs:
      displayName: NuGet.org push
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'Nuget Org'